version: '3.8'
services:
  web:
    build: .
    image: moesif-phoenix-example:latest
    environment:
      - MOESIF_API_URL=http://echo:5678/api/example
    ports:
      - "4000:4000"
    depends_on:
      - echo
  echo:
    image: hashicorp/http-echo
    command:
      - "-text=Hello from docker-compose"
    ports:
      - "5678:5678"